/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.maersk.Geography.smds.operations.MSK;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Geography Parent details */
@org.apache.avro.specific.AvroGenerated
public class GeographyParentDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7191061038682627634L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GeographyParentDetails\",\"namespace\":\"com.maersk.Geography.smds.operations.MSK\",\"doc\":\"Geography Parent details\",\"fields\":[{\"name\":\"getParentRowId\",\"type\":[\"null\",\"string\"]},{\"name\":\"Name\",\"type\":[\"null\",\"string\"]},{\"name\":\"Type\",\"type\":[\"null\",\"string\"]},{\"name\":\"GeographyParentAlternateCodeDetails\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"GeographyParentAlternateCode\",\"doc\":\"Geography Parent AlternateCode details\",\"fields\":[{\"name\":\"CodeType\",\"type\":[\"null\",\"string\"]},{\"name\":\"Code\",\"type\":[\"null\",\"string\"]}]}}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GeographyParentDetails> ENCODER =
      new BinaryMessageEncoder<GeographyParentDetails>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GeographyParentDetails> DECODER =
      new BinaryMessageDecoder<GeographyParentDetails>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<GeographyParentDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<GeographyParentDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GeographyParentDetails>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this GeographyParentDetails to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a GeographyParentDetails from a ByteBuffer. */
  public static GeographyParentDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence getParentRowId;
  @Deprecated public java.lang.CharSequence Name;
  @Deprecated public java.lang.CharSequence Type;
  @Deprecated public java.util.List<com.maersk.Geography.smds.operations.MSK.GeographyParentAlternateCode> GeographyParentAlternateCodeDetails;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GeographyParentDetails() {}

  /**
   * All-args constructor.
   * @param getParentRowId The new value for getParentRowId
   * @param Name The new value for Name
   * @param Type The new value for Type
   * @param GeographyParentAlternateCodeDetails The new value for GeographyParentAlternateCodeDetails
   */
  public GeographyParentDetails(java.lang.CharSequence getParentRowId, java.lang.CharSequence Name, java.lang.CharSequence Type, java.util.List<com.maersk.Geography.smds.operations.MSK.GeographyParentAlternateCode> GeographyParentAlternateCodeDetails) {
    this.getParentRowId = getParentRowId;
    this.Name = Name;
    this.Type = Type;
    this.GeographyParentAlternateCodeDetails = GeographyParentAlternateCodeDetails;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return getParentRowId;
    case 1: return Name;
    case 2: return Type;
    case 3: return GeographyParentAlternateCodeDetails;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: getParentRowId = (java.lang.CharSequence)value$; break;
    case 1: Name = (java.lang.CharSequence)value$; break;
    case 2: Type = (java.lang.CharSequence)value$; break;
    case 3: GeographyParentAlternateCodeDetails = (java.util.List<com.maersk.Geography.smds.operations.MSK.GeographyParentAlternateCode>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'getParentRowId' field.
   * @return The value of the 'getParentRowId' field.
   */
  public java.lang.CharSequence getGetParentRowId() {
    return getParentRowId;
  }

  /**
   * Sets the value of the 'getParentRowId' field.
   * @param value the value to set.
   */
  public void setGetParentRowId(java.lang.CharSequence value) {
    this.getParentRowId = value;
  }

  /**
   * Gets the value of the 'Name' field.
   * @return The value of the 'Name' field.
   */
  public java.lang.CharSequence getName() {
    return Name;
  }

  /**
   * Sets the value of the 'Name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.Name = value;
  }

  /**
   * Gets the value of the 'Type' field.
   * @return The value of the 'Type' field.
   */
  public java.lang.CharSequence getType() {
    return Type;
  }

  /**
   * Sets the value of the 'Type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.Type = value;
  }

  /**
   * Gets the value of the 'GeographyParentAlternateCodeDetails' field.
   * @return The value of the 'GeographyParentAlternateCodeDetails' field.
   */
  public java.util.List<com.maersk.Geography.smds.operations.MSK.GeographyParentAlternateCode> getGeographyParentAlternateCodeDetails() {
    return GeographyParentAlternateCodeDetails;
  }

  /**
   * Sets the value of the 'GeographyParentAlternateCodeDetails' field.
   * @param value the value to set.
   */
  public void setGeographyParentAlternateCodeDetails(java.util.List<com.maersk.Geography.smds.operations.MSK.GeographyParentAlternateCode> value) {
    this.GeographyParentAlternateCodeDetails = value;
  }

  /**
   * Creates a new GeographyParentDetails RecordBuilder.
   * @return A new GeographyParentDetails RecordBuilder
   */
  public static com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder newBuilder() {
    return new com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder();
  }

  /**
   * Creates a new GeographyParentDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GeographyParentDetails RecordBuilder
   */
  public static com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder newBuilder(com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder other) {
    return new com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder(other);
  }

  /**
   * Creates a new GeographyParentDetails RecordBuilder by copying an existing GeographyParentDetails instance.
   * @param other The existing instance to copy.
   * @return A new GeographyParentDetails RecordBuilder
   */
  public static com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder newBuilder(com.maersk.Geography.smds.operations.MSK.GeographyParentDetails other) {
    return new com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder(other);
  }

  /**
   * RecordBuilder for GeographyParentDetails instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GeographyParentDetails>
    implements org.apache.avro.data.RecordBuilder<GeographyParentDetails> {

    private java.lang.CharSequence getParentRowId;
    private java.lang.CharSequence Name;
    private java.lang.CharSequence Type;
    private java.util.List<com.maersk.Geography.smds.operations.MSK.GeographyParentAlternateCode> GeographyParentAlternateCodeDetails;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.getParentRowId)) {
        this.getParentRowId = data().deepCopy(fields()[0].schema(), other.getParentRowId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Name)) {
        this.Name = data().deepCopy(fields()[1].schema(), other.Name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Type)) {
        this.Type = data().deepCopy(fields()[2].schema(), other.Type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.GeographyParentAlternateCodeDetails)) {
        this.GeographyParentAlternateCodeDetails = data().deepCopy(fields()[3].schema(), other.GeographyParentAlternateCodeDetails);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing GeographyParentDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(com.maersk.Geography.smds.operations.MSK.GeographyParentDetails other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.getParentRowId)) {
        this.getParentRowId = data().deepCopy(fields()[0].schema(), other.getParentRowId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Name)) {
        this.Name = data().deepCopy(fields()[1].schema(), other.Name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Type)) {
        this.Type = data().deepCopy(fields()[2].schema(), other.Type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.GeographyParentAlternateCodeDetails)) {
        this.GeographyParentAlternateCodeDetails = data().deepCopy(fields()[3].schema(), other.GeographyParentAlternateCodeDetails);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'getParentRowId' field.
      * @return The value.
      */
    public java.lang.CharSequence getGetParentRowId() {
      return getParentRowId;
    }

    /**
      * Sets the value of the 'getParentRowId' field.
      * @param value The value of 'getParentRowId'.
      * @return This builder.
      */
    public com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder setGetParentRowId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.getParentRowId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'getParentRowId' field has been set.
      * @return True if the 'getParentRowId' field has been set, false otherwise.
      */
    public boolean hasGetParentRowId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'getParentRowId' field.
      * @return This builder.
      */
    public com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder clearGetParentRowId() {
      getParentRowId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return Name;
    }

    /**
      * Sets the value of the 'Name' field.
      * @param value The value of 'Name'.
      * @return This builder.
      */
    public com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Name' field has been set.
      * @return True if the 'Name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Name' field.
      * @return This builder.
      */
    public com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder clearName() {
      Name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return Type;
    }

    /**
      * Sets the value of the 'Type' field.
      * @param value The value of 'Type'.
      * @return This builder.
      */
    public com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder setType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.Type = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Type' field has been set.
      * @return True if the 'Type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Type' field.
      * @return This builder.
      */
    public com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder clearType() {
      Type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'GeographyParentAlternateCodeDetails' field.
      * @return The value.
      */
    public java.util.List<com.maersk.Geography.smds.operations.MSK.GeographyParentAlternateCode> getGeographyParentAlternateCodeDetails() {
      return GeographyParentAlternateCodeDetails;
    }

    /**
      * Sets the value of the 'GeographyParentAlternateCodeDetails' field.
      * @param value The value of 'GeographyParentAlternateCodeDetails'.
      * @return This builder.
      */
    public com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder setGeographyParentAlternateCodeDetails(java.util.List<com.maersk.Geography.smds.operations.MSK.GeographyParentAlternateCode> value) {
      validate(fields()[3], value);
      this.GeographyParentAlternateCodeDetails = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'GeographyParentAlternateCodeDetails' field has been set.
      * @return True if the 'GeographyParentAlternateCodeDetails' field has been set, false otherwise.
      */
    public boolean hasGeographyParentAlternateCodeDetails() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'GeographyParentAlternateCodeDetails' field.
      * @return This builder.
      */
    public com.maersk.Geography.smds.operations.MSK.GeographyParentDetails.Builder clearGeographyParentAlternateCodeDetails() {
      GeographyParentAlternateCodeDetails = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GeographyParentDetails build() {
      try {
        GeographyParentDetails record = new GeographyParentDetails();
        record.getParentRowId = fieldSetFlags()[0] ? this.getParentRowId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Name = fieldSetFlags()[1] ? this.Name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.Type = fieldSetFlags()[2] ? this.Type : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.GeographyParentAlternateCodeDetails = fieldSetFlags()[3] ? this.GeographyParentAlternateCodeDetails : (java.util.List<com.maersk.Geography.smds.operations.MSK.GeographyParentAlternateCode>) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GeographyParentDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<GeographyParentDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GeographyParentDetails>
    READER$ = (org.apache.avro.io.DatumReader<GeographyParentDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
