/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.maersk.Geography.smds.operations.MSK;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Geography BDA AlternateCode details */
@org.apache.avro.specific.AvroGenerated
public class GeographyBDAAlternateCode extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -627014317171794059L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GeographyBDAAlternateCode\",\"namespace\":\"com.maersk.Geography.smds.operations.MSK\",\"doc\":\"Geography BDA AlternateCode details\",\"fields\":[{\"name\":\"CodeType\",\"type\":[\"null\",\"string\"]},{\"name\":\"Code\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GeographyBDAAlternateCode> ENCODER =
      new BinaryMessageEncoder<GeographyBDAAlternateCode>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GeographyBDAAlternateCode> DECODER =
      new BinaryMessageDecoder<GeographyBDAAlternateCode>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<GeographyBDAAlternateCode> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<GeographyBDAAlternateCode> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GeographyBDAAlternateCode>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this GeographyBDAAlternateCode to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a GeographyBDAAlternateCode from a ByteBuffer. */
  public static GeographyBDAAlternateCode fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence CodeType;
  @Deprecated public java.lang.CharSequence Code;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GeographyBDAAlternateCode() {}

  /**
   * All-args constructor.
   * @param CodeType The new value for CodeType
   * @param Code The new value for Code
   */
  public GeographyBDAAlternateCode(java.lang.CharSequence CodeType, java.lang.CharSequence Code) {
    this.CodeType = CodeType;
    this.Code = Code;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CodeType;
    case 1: return Code;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CodeType = (java.lang.CharSequence)value$; break;
    case 1: Code = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CodeType' field.
   * @return The value of the 'CodeType' field.
   */
  public java.lang.CharSequence getCodeType() {
    return CodeType;
  }

  /**
   * Sets the value of the 'CodeType' field.
   * @param value the value to set.
   */
  public void setCodeType(java.lang.CharSequence value) {
    this.CodeType = value;
  }

  /**
   * Gets the value of the 'Code' field.
   * @return The value of the 'Code' field.
   */
  public java.lang.CharSequence getCode() {
    return Code;
  }

  /**
   * Sets the value of the 'Code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.CharSequence value) {
    this.Code = value;
  }

  /**
   * Creates a new GeographyBDAAlternateCode RecordBuilder.
   * @return A new GeographyBDAAlternateCode RecordBuilder
   */
  public static com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode.Builder newBuilder() {
    return new com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode.Builder();
  }

  /**
   * Creates a new GeographyBDAAlternateCode RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GeographyBDAAlternateCode RecordBuilder
   */
  public static com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode.Builder newBuilder(com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode.Builder other) {
    return new com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode.Builder(other);
  }

  /**
   * Creates a new GeographyBDAAlternateCode RecordBuilder by copying an existing GeographyBDAAlternateCode instance.
   * @param other The existing instance to copy.
   * @return A new GeographyBDAAlternateCode RecordBuilder
   */
  public static com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode.Builder newBuilder(com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode other) {
    return new com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode.Builder(other);
  }

  /**
   * RecordBuilder for GeographyBDAAlternateCode instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GeographyBDAAlternateCode>
    implements org.apache.avro.data.RecordBuilder<GeographyBDAAlternateCode> {

    private java.lang.CharSequence CodeType;
    private java.lang.CharSequence Code;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CodeType)) {
        this.CodeType = data().deepCopy(fields()[0].schema(), other.CodeType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Code)) {
        this.Code = data().deepCopy(fields()[1].schema(), other.Code);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing GeographyBDAAlternateCode instance
     * @param other The existing instance to copy.
     */
    private Builder(com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.CodeType)) {
        this.CodeType = data().deepCopy(fields()[0].schema(), other.CodeType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Code)) {
        this.Code = data().deepCopy(fields()[1].schema(), other.Code);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'CodeType' field.
      * @return The value.
      */
    public java.lang.CharSequence getCodeType() {
      return CodeType;
    }

    /**
      * Sets the value of the 'CodeType' field.
      * @param value The value of 'CodeType'.
      * @return This builder.
      */
    public com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode.Builder setCodeType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.CodeType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CodeType' field has been set.
      * @return True if the 'CodeType' field has been set, false otherwise.
      */
    public boolean hasCodeType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CodeType' field.
      * @return This builder.
      */
    public com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode.Builder clearCodeType() {
      CodeType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCode() {
      return Code;
    }

    /**
      * Sets the value of the 'Code' field.
      * @param value The value of 'Code'.
      * @return This builder.
      */
    public com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode.Builder setCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Code = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Code' field has been set.
      * @return True if the 'Code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Code' field.
      * @return This builder.
      */
    public com.maersk.Geography.smds.operations.MSK.GeographyBDAAlternateCode.Builder clearCode() {
      Code = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GeographyBDAAlternateCode build() {
      try {
        GeographyBDAAlternateCode record = new GeographyBDAAlternateCode();
        record.CodeType = fieldSetFlags()[0] ? this.CodeType : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Code = fieldSetFlags()[1] ? this.Code : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GeographyBDAAlternateCode>
    WRITER$ = (org.apache.avro.io.DatumWriter<GeographyBDAAlternateCode>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GeographyBDAAlternateCode>
    READER$ = (org.apache.avro.io.DatumReader<GeographyBDAAlternateCode>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
